"""Update LdapConfguration

Revision ID: 72dd6fe2e968
Revises: cc4b021211f2
Create Date: 2023-01-17 22:22:15.748488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dd6fe2e968'
down_revision = 'cc4b021211f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('cacert_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LdapConfiguration', 'cacert_path')
    # ### end Alembic commands ###
