"""Update LdapConfguration

Revision ID: 97acb91fc140
Revises: 72dd6fe2e968
Create Date: 2023-01-17 22:52:17.632794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97acb91fc140'
down_revision = '72dd6fe2e968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('users_approval', sa.Boolean(), nullable=True))
    op.drop_column('LdapConfiguration', 'anonymous_bind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('anonymous_bind', sa.BOOLEAN(), nullable=True))
    op.drop_column('LdapConfiguration', 'users_approval')
    # ### end Alembic commands ###
