"""FlaskLDAP3 attributes

Revision ID: cc4b021211f2
Revises: 4aa66a157e80
Create Date: 2023-01-16 21:38:03.994542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4b021211f2'
down_revision = '4aa66a157e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('server_port', sa.Integer(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('use_tls', sa.Boolean(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('anonymous_bind', sa.Boolean(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('users_dn', sa.String(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('groups_dn', sa.String(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('user_rdn_attr', sa.String(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('user_login_attr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LdapConfiguration', 'user_login_attr')
    op.drop_column('LdapConfiguration', 'user_rdn_attr')
    op.drop_column('LdapConfiguration', 'groups_dn')
    op.drop_column('LdapConfiguration', 'users_dn')
    op.drop_column('LdapConfiguration', 'anonymous_bind')
    op.drop_column('LdapConfiguration', 'use_tls')
    op.drop_column('LdapConfiguration', 'server_port')
    # ### end Alembic commands ###
