version: '3.8'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    restart: always
    environment:
      - POSTGRES_USER=grepmarx
      - POSTGRES_PASSWORD=!!!CHANGE_ME!!!
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  grepmarx:
    restart: always
    volumes: 
      - gpx-data:/opt/grepmarx/data
    build: .
    links:
      - redis
      - db
    depends_on:
      - redis
      - db

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "5000:5000"
    links:
      - grepmarx
    depends_on: 
      - grepmarx

volumes:
    db-data:
    gpx-data:
