version: '3.8'
services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - web_network

  grepmarx:
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=***REMOVED***
      - CELERY_BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
    build: .
    networks:
      - web_network
    links:
      - redis
    depends_on:
      - redis

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./nginx/ssl/cert.crt:/etc/ssl/certs/cert.crt
      # - ./nginx/ssl/cert.key:/etc/ssl/private/cert.key
    networks:
      - web_network
    depends_on: 
      - grepmarx
  db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=grepmarx
        - POSTGRES_PASSWORD=!!!CHANGE_ME!!!
      volumes: 
        - db:/var/lib/postgresql/data
      networks:
        - web_network

volumes:
    db:

networks:
  web_network:
    driver: bridge
