"""LDAP configuration properties

Revision ID: 045401a0856b
Revises: a125084435a2
Create Date: 2023-01-04 11:42:19.766066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045401a0856b'
down_revision = 'a125084435a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LdapConf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('bind_Dnd', sa.String(), nullable=False),
    sa.Column('search_base', sa.String(), nullable=False),
    sa.Column('search_filter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('User', sa.Column('local', sa.Boolean(), nullable=True))
    op.drop_constraint('User_username_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_username_key', 'User', ['username'])
    op.drop_column('User', 'local')
    op.drop_table('LdapConf')
    # ### end Alembic commands ###
