"""Clean LDAP config model

Revision ID: 4aa66a157e80
Revises: 6555671bee72
Create Date: 2023-01-08 23:49:28.741953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa66a157e80'
down_revision = '6555671bee72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LdapConfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_host', sa.String(), nullable=True),
    sa.Column('bind_dn', sa.String(), nullable=True),
    sa.Column('bind_password', sa.String(), nullable=True),
    sa.Column('base_dn', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LdapConf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LdapConf',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('bind_Dnd', sa.VARCHAR(), nullable=False),
    sa.Column('search_base', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LdapConfiguration')
    # ### end Alembic commands ###
