"""Add anonymous bind in LDAP configuration

Revision ID: 69dae5740268
Revises: f7720d9a4e1b
Create Date: 2023-01-10 21:09:52.312804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69dae5740268'
down_revision = 'f7720d9a4e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('anonymous_bind', sa.Boolean(), nullable=True))
    op.alter_column('LdapConfiguration', 'use_tls',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LdapConfiguration', 'use_tls',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('LdapConfiguration', 'anonymous_bind')
    # ### end Alembic commands ###
