"""empty message

Revision ID: 8a5c5c61684e
Revises: 
Create Date: 2021-12-16 17:10:55.371986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5c5c61684e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AnalysisError')
    op.drop_table('AnalysisErrorSpan')
    op.drop_constraint(None, 'Position', type_='foreignkey')
    op.drop_column('Position', 'span_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Position', sa.Column('span_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'Position', 'AnalysisErrorSpan', ['span_id'], ['id'])
    op.create_table('AnalysisErrorSpan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_error_id', sa.INTEGER(), nullable=False),
    sa.Column('file', sa.VARCHAR(), nullable=False),
    sa.Column('source_hash', sa.VARCHAR(), nullable=True),
    sa.Column('context_start', sa.VARCHAR(), nullable=True),
    sa.Column('context_end', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_error_id'], ['AnalysisError.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AnalysisError',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('rule_id', sa.VARCHAR(), nullable=True),
    sa.Column('error_type', sa.VARCHAR(), nullable=True),
    sa.Column('help_msg', sa.VARCHAR(), nullable=True),
    sa.Column('long_msg', sa.VARCHAR(), nullable=True),
    sa.Column('short_msg', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['Analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
