"""Flask-Ldap3-Login attributes

Revision ID: 8ab1f2133191
Revises: 4aa66a157e80
Create Date: 2023-01-17 23:33:13.563247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab1f2133191'
down_revision = '4aa66a157e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LdapConfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ldap_activated', sa.Boolean(), nullable=False),
    sa.Column('server_host', sa.String(), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('cacert_path', sa.String(), nullable=True),
    sa.Column('users_approval', sa.Boolean(), nullable=True),
    sa.Column('bind_dn', sa.String(), nullable=True),
    sa.Column('bind_password', sa.String(), nullable=True),
    sa.Column('base_dn', sa.String(), nullable=True),
    sa.Column('users_dn', sa.String(), nullable=True),
    sa.Column('groups_dn', sa.String(), nullable=True),
    sa.Column('user_rdn_attr', sa.String(), nullable=True),
    sa.Column('user_login_attr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LdapConf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LdapConf',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('bind_Dnd', sa.VARCHAR(), nullable=False),
    sa.Column('search_base', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LdapConfiguration')
    # ### end Alembic commands ###
