"""1 DEPENDENCY SCAN

Revision ID: e61e60056d50
Revises: c9af49fc09c4
Create Date: 2023-02-02 23:00:45.973409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61e60056d50'
down_revision = 'c9af49fc09c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VulnerableDependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('common_id', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('purl', sa.String(), nullable=True),
    sa.Column('package_type', sa.String(), nullable=True),
    sa.Column('package_usage', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('fix_version', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('cvss_score', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('related_urls', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['Analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VulnerableDependency')
    # ### end Alembic commands ###
