"""Update LdapConfiguration

Revision ID: f7720d9a4e1b
Revises: 4aa66a157e80
Create Date: 2023-01-09 20:40:29.013355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7720d9a4e1b'
down_revision = '4aa66a157e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('ldap_activated', sa.Boolean(), nullable=False))
    op.add_column('LdapConfiguration', sa.Column('server_host', sa.String(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('server_port', sa.Integer(), nullable=True))
    op.add_column('LdapConfiguration', sa.Column('use_tls', sa.Integer(), nullable=True))
    op.drop_column('LdapConfiguration', 'server_uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LdapConfiguration', sa.Column('server_uri', sa.VARCHAR(), nullable=True))
    op.drop_column('LdapConfiguration', 'use_tls')
    op.drop_column('LdapConfiguration', 'server_port')
    op.drop_column('LdapConfiguration', 'server_host')
    op.drop_column('LdapConfiguration', 'ldap_activated')
    # ### end Alembic commands ###
