"""2 RULE IMPACT LIKELIHOOD CONFIDENCE

Revision ID: fbe5a034063a
Revises: 792cdb4dabcc
Create Date: 2023-02-17 15:36:34.263169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe5a034063a'
down_revision = '792cdb4dabcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rule', sa.Column('likelihood', sa.String(), nullable=True))
    op.add_column('Rule', sa.Column('impact', sa.String(), nullable=True))
    op.add_column('Rule', sa.Column('confidence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Rule', 'confidence')
    op.drop_column('Rule', 'impact')
    op.drop_column('Rule', 'likelihood')
    # ### end Alembic commands ###
